name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name NetworkMonitor network_monitor_full.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: NetworkMonitor
          path: dist/NetworkMonitor.exe
